### ISSUE TITLE
CIC_DEV role is not allowing proms patterns to be registered in urls.py

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1121]
this is the existing code ( <app root>/rdrf/rdrf/urls.py )

```
if settings.SYSTEM_ROLE == SystemRoles.CIC_PROMS:
    urlpatterns = proms_patterns
else:
    urlpatterns = normalpatterns
```

Should be:
```
if settings.SYSTEM_ROLE in [SystemRoles.CIC_PROMS, SystemRoles.CIC_DEV]:
    urlpatterns = proms_patterns
else:
    urlpatterns = normalpatterns
```

**Comment by id2359** [comment]
You will need to change the SYSTEM_ROLE env var in docker-compose.yml

like this:
```
runserver:
    extends:
      file: docker-compose-common.yml
      service: runserver
    environment:
      - DJANGO_FIXTURES=dev
      - DESIGN_MODE=1
      - **SYSTEM_ROLE=CIC_DEV**
```
