### ISSUE TITLE
Management command to re-populate redis umrns

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1925]

**Comment by jithendralal** [comment]
This management command requires the following:

'blackboard' in settings:
```
CACHES['blackboard'] = {
    "BACKEND": "django_redis.cache.RedisCache",
    "LOCATION": env.getlist("cache", ["redis://rediscache:6379/9"]),
    "TIMEOUT": 3600,
    "OPTIONS": {
        "CLIENT_CLASS": "django_redis.client.DefaultClient"
    },
    "KEY_PREFIX": "rdrf_if_"
}
```
docker_compose_common.yml
```
  rediscache:
    image: redis:3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
```
